# Spring配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  # 指定配置环境 dev(开发环境),prod(生产环境),test(测试环境)
  profiles:
    active: dev
  # redis 配置
  redis:
    # 地址
    host: 127.0.0.1
    # 端口，默认为6379
    port: 6379
    # 密码
    password:
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.zjj.dto
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql

# 密码 RSA加密传输，前端公钥加密，后端私钥解密
rsa:
  privateKey: MIIBVAIBADANBgkqhkiG9w0BAQEFAASCAT4wggE6AgEAAkEAzV7ajGcCIpaYczkA89seVkZzWg17gsGMp7llgINTJqKVzVwDeGmkklHjyT+FEUMueCJ5a4dg3d5xEz1VoYpAzQIDAQABAkBV3yKM8IlhAw0tqJkwXd+6fWzAK8EINHvmqcu6R68eCL/NOL8Hfrm7TBMEY16kp8GyNiAgXtwViyVYWG7TcZHhAiEA5+FKiWFtcO4Y4CR99B+HCYV8N+2/HjhDg1rM/qtEa+kCIQDiu6SyIWT9QuFkbD4TntuiEO287FFEONCgsNO/LHPzRQIhANRhmx19aPn4ejxB8EM65TopUv7++P+61MtozT2srHyRAiAXofVdt8td9o2luP6Tbvh3oQoWqg8ibEWaqjO39nszfQIgBWmfD+ESyhS2s8lkHnOMrMkwluMNRTRzz+Jj0tNQhpo=

# 腾讯云短信服务配置
qcloudSms:
  # SDK AppID
  appId: 1400473906
  # SDK AppKey
  appKey: f82be15572e80c4c4561c3170e596d37
  # 签名
  smsSign: Keingran预约网
  # 短信模板 ID
  templateId: 845812

